Completed String manipulation 2 - Mohamed
Mohamed-Elmessiry/c0321-code-solutions pull request #52
Opened 2021-04-03 22:22 UTC by Mohamed-Elmessiry

<img width="1440" alt="Screen Shot 2021-04-03 at 6 18 47 PM" src="https://user-images.githubusercontent.com/69738204/113492980-9380ae80-94a9-11eb-9485-99f35b74b2eb.png">

2021-04-05 17:48 UTC, codingcodymiller requested changes
Great start here, please see my notes

2021-04-05 17:48 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +  }
This is for a single word, there should be no need for a loop

2021-04-05 17:48 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-words.js
> +  var k = [];
Please stop using single letters for your variable names, with the exception of `i`. Your variables should be named to describe their purpose, _always_

2021-04-05 17:48 UTC, codingcodymiller commented on string-manipulation-2/src/truncate.js
> +  var nstring = '';
`nstring`? What does this mean?

2021-05-03 18:02 UTC, thebearingedge approved these changes

2021-05-03 18:33 UTC, merged